---
- hosts: webserver
  become: true
  tasks: 
    - name: Install apache
      apt: name={{item}} state=present update_cache=yes
      with_items:
       - apache2
       - libapache2-mod-wsgi
       - python-pip
       - python-virtualenv
       
    - name: Ensure apache is running
      service: name=apache2 state=started enabled=yes
