---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update Cache
      apt: update_cache=yes cache_valid_time=86400
      
- include: control.yml
- include: mariadb.yml
- include: webserver.yml
- include: loadbalancer.yml
