---
- hosts: db01
  become: true
  roles:
    - role: mariadb
      db_name: "{{ demo_app_db_name }}"
      db_user_name: "{{ demo_app_db_user_name }}"
      db_user_password: "{{ demo_app_db_user_password }}"
      db_user_host: '%'
