---
# Bring Stack Down
- hosts: loadbalancer
  become: true
  tasks: 
    - name: Bring down loadbalancer
      service: name=nginx state=stopped
      
    - name: Ensure all connections are gone
      wait_for: port=80 state=drained 
      
# Bring Webservices down 
- hosts: webserver
  become: true
  tasks: 
    - name: Bring down web-services
      service: name=apache2 state=stopped
      
    - name: Ensure all connections are gone
      wait_for: port=80 state=stopped 
      
# Restart Maria DB
- hosts: db01
  become: true
  tasks: 
    - name: Restart DB
      service: name=mysql state=restarted
      
    - name: Ensure mysql is started
      wait_for: port=3306 state=started
      
# Bring Webservices Up
- hosts: webserver
  become: true
  tasks: 
    - name: Bring up web-services
      service: name=apache2 state=started
      
    - name: Ensure apache2 is up
      wait_for: port=80 state=started 
      
# Bring Loadbalancer Up
- hosts: loadbalancer
  become: true
  tasks: 
    - name: Bring up loadbalancer
      service: name=nginx state=started
      
    - name: Ensure nginx is up
      wait_for: port=80 state=started 
